#pragma once

#include <libloading/Library.hpp>

#include <sql.h>
#include <sqlext.h>
#include <sqlucode.h>

class Odbc : libloading::Library
{
public:
   Odbc(libloading::ILibraryLoader& loader)
    : libloading::Library(loader, {/*on WIN32*/"odbc32", /*for unix odbc*/"odbc"})
   {}

   // sql.h
   LIBL_STDCALL(SQLAllocConnect, SQLRETURN(SQLHENV EnvironmentHandle, SQLHDBC *ConnectionHandle));
   LIBL_STDCALL(SQLAllocEnv, SQLRETURN(SQLHENV *EnvironmentHandle));
   LIBL_STDCALL(SQLAllocHandle, SQLRETURN(SQLSMALLINT HandleType, SQLHANDLE InputHandle, SQLHANDLE *OutputHandle));
   LIBL_STDCALL(SQLAllocStmt, SQLRETURN(SQLHDBC ConnectionHandle, SQLHSTMT *StatementHandle));
   LIBL_STDCALL(SQLBindCol, SQLRETURN(SQLHSTMT StatementHandle, SQLUSMALLINT ColumnNumber, SQLSMALLINT TargetType, SQLPOINTER TargetValue, SQLLEN BufferLength, SQLLEN *StrLen_or_Ind));
   LIBL_STDCALL(SQLBindParam, SQLRETURN(SQLHSTMT StatementHandle, SQLUSMALLINT ParameterNumber, SQLSMALLINT ValueType, SQLSMALLINT ParameterType, SQLULEN LengthPrecision, SQLSMALLINT ParameterScale, SQLPOINTER ParameterValue, SQLLEN *StrLen_or_Ind));
   LIBL_STDCALL(SQLCancel, SQLRETURN(SQLHSTMT StatementHandle));
#if (ODBCVER >= 0x0380)
   //LIBL_STDCALL(SQLCancelHandle, SQLRETURN(SQLSMALLINT HandleType, SQLHANDLE InputHandle));
#endif
   LIBL_STDCALL(SQLCloseCursor, SQLRETURN(SQLHSTMT StatementHandle));
   LIBL_STDCALL(SQLColAttribute, SQLRETURN(SQLHSTMT StatementHandle, SQLUSMALLINT ColumnNumber, SQLUSMALLINT FieldIdentifier, SQLPOINTER CharacterAttribute, SQLSMALLINT BufferLength, SQLSMALLINT *StringLength, SQLLEN *NumericAttribute));
   LIBL_STDCALL(SQLColumns, SQLRETURN(SQLHSTMT StatementHandle, SQLCHAR *CatalogName, SQLSMALLINT NameLength1, SQLCHAR *SchemaName, SQLSMALLINT NameLength2, SQLCHAR *TableName, SQLSMALLINT NameLength3, SQLCHAR *ColumnName, SQLSMALLINT NameLength4));
   LIBL_STDCALL(SQLConnect, SQLRETURN(SQLHDBC ConnectionHandle, SQLCHAR *ServerName, SQLSMALLINT NameLength1, SQLCHAR *UserName, SQLSMALLINT NameLength2, SQLCHAR *Authentication, SQLSMALLINT NameLength3));
   LIBL_STDCALL(SQLCopyDesc, SQLRETURN(SQLHDESC SourceDescHandle, SQLHDESC TargetDescHandle));
   LIBL_STDCALL(SQLDataSources, SQLRETURN(SQLHENV EnvironmentHandle, SQLUSMALLINT Direction, SQLCHAR *ServerName, SQLSMALLINT BufferLength1, SQLSMALLINT *NameLength1, SQLCHAR *Description, SQLSMALLINT BufferLength2, SQLSMALLINT *NameLength2));
   LIBL_STDCALL(SQLDescribeCol, SQLRETURN(SQLHSTMT StatementHandle, SQLUSMALLINT ColumnNumber, SQLCHAR *ColumnName, SQLSMALLINT BufferLength, SQLSMALLINT *NameLength, SQLSMALLINT *DataType, SQLULEN *ColumnSize, SQLSMALLINT *DecimalDigits, SQLSMALLINT *Nullable));
   LIBL_STDCALL(SQLDisconnect, SQLRETURN(SQLHDBC ConnectionHandle));
   LIBL_STDCALL(SQLEndTran, SQLRETURN(SQLSMALLINT HandleType, SQLHANDLE Handle, SQLSMALLINT CompletionType));
   LIBL_STDCALL(SQLError, SQLRETURN(SQLHENV EnvironmentHandle, SQLHDBC ConnectionHandle, SQLHSTMT StatementHandle, SQLCHAR *Sqlstate, SQLINTEGER *NativeError, SQLCHAR *MessageText, SQLSMALLINT BufferLength, SQLSMALLINT *TextLength));
   LIBL_STDCALL(SQLExecDirect, SQLRETURN(SQLHSTMT StatementHandle, SQLCHAR *StatementText, SQLINTEGER TextLength));
   LIBL_STDCALL(SQLExecute, SQLRETURN(SQLHSTMT StatementHandle));
   LIBL_STDCALL(SQLFetch, SQLRETURN(SQLHSTMT StatementHandle));
   LIBL_STDCALL(SQLFetchScroll, SQLRETURN(SQLHSTMT StatementHandle, SQLSMALLINT FetchOrientation, SQLLEN FetchOffset));
   LIBL_STDCALL(SQLFreeConnect, SQLRETURN(SQLHDBC ConnectionHandle));
   LIBL_STDCALL(SQLFreeEnv, SQLRETURN(SQLHENV EnvironmentHandle));
   LIBL_STDCALL(SQLFreeHandle, SQLRETURN(SQLSMALLINT HandleType, SQLHANDLE Handle));
   LIBL_STDCALL(SQLFreeStmt, SQLRETURN(SQLHSTMT StatementHandle, SQLUSMALLINT Option));
   LIBL_STDCALL(SQLGetConnectAttr, SQLRETURN(SQLHDBC ConnectionHandle, SQLINTEGER Attribute, SQLPOINTER Value, SQLINTEGER BufferLength, SQLINTEGER *StringLength));
   LIBL_STDCALL(SQLGetConnectOption, SQLRETURN(SQLHDBC ConnectionHandle, SQLUSMALLINT Option, SQLPOINTER Value));
   LIBL_STDCALL(SQLGetCursorName, SQLRETURN(SQLHSTMT StatementHandle, SQLCHAR *CursorName, SQLSMALLINT BufferLength, SQLSMALLINT *NameLength));
   LIBL_STDCALL(SQLGetData, SQLRETURN(SQLHSTMT StatementHandle, SQLUSMALLINT ColumnNumber, SQLSMALLINT TargetType, SQLPOINTER TargetValue, SQLLEN BufferLength, SQLLEN *StrLen_or_Ind));
   LIBL_STDCALL(SQLGetDescRec, SQLRETURN(SQLHDESC DescriptorHandle, SQLSMALLINT RecNumber, SQLCHAR *Name, SQLSMALLINT BufferLength, SQLSMALLINT *StringLength, SQLSMALLINT *Type, SQLSMALLINT *SubType, SQLLEN *Length, SQLSMALLINT *Precision, SQLSMALLINT *Scale, SQLSMALLINT *Nullable));
   LIBL_STDCALL(SQLGetDiagField, SQLRETURN(SQLSMALLINT HandleType, SQLHANDLE Handle, SQLSMALLINT RecNumber, SQLSMALLINT DiagIdentifier, SQLPOINTER DiagInfo, SQLSMALLINT BufferLength, SQLSMALLINT *StringLength));
   LIBL_STDCALL(SQLGetDiagRec, SQLRETURN(SQLSMALLINT HandleType, SQLHANDLE Handle, SQLSMALLINT RecNumber, SQLCHAR *Sqlstate, SQLINTEGER *NativeError, SQLCHAR *MessageText, SQLSMALLINT BufferLength, SQLSMALLINT *TextLength));
   LIBL_STDCALL(SQLGetEnvAttr, SQLRETURN(SQLHENV EnvironmentHandle, SQLINTEGER Attribute, SQLPOINTER Value, SQLINTEGER BufferLength, SQLINTEGER *StringLength));
   LIBL_STDCALL(SQLGetFunctions, SQLRETURN(SQLHDBC ConnectionHandle, SQLUSMALLINT FunctionId, SQLUSMALLINT *Supported));
   LIBL_STDCALL(SQLGetInfo, SQLRETURN(SQLHDBC ConnectionHandle, SQLUSMALLINT InfoType, SQLPOINTER InfoValue, SQLSMALLINT BufferLength, SQLSMALLINT *StringLength));
   LIBL_STDCALL(SQLGetStmtAttr, SQLRETURN(SQLHSTMT StatementHandle, SQLINTEGER Attribute, SQLPOINTER Value, SQLINTEGER BufferLength, SQLINTEGER *StringLength));
   LIBL_STDCALL(SQLGetStmtOption, SQLRETURN(SQLHSTMT StatementHandle, SQLUSMALLINT Option, SQLPOINTER Value));
   LIBL_STDCALL(SQLGetTypeInfo, SQLRETURN(SQLHSTMT StatementHandle, SQLSMALLINT DataType));
   LIBL_STDCALL(SQLNumResultCols, SQLRETURN(SQLHSTMT StatementHandle, SQLSMALLINT *ColumnCount));
   LIBL_STDCALL(SQLParamData, SQLRETURN(SQLHSTMT StatementHandle, SQLPOINTER *Value));
   LIBL_STDCALL(SQLPrepare, SQLRETURN(SQLHSTMT StatementHandle, SQLCHAR *StatementText, SQLINTEGER TextLength));
   LIBL_STDCALL(SQLPutData, SQLRETURN(SQLHSTMT StatementHandle, SQLPOINTER Data, SQLLEN StrLen_or_Ind));
   LIBL_STDCALL(SQLRowCount, SQLRETURN(SQLHSTMT StatementHandle, SQLLEN *RowCount));
   LIBL_STDCALL(SQLSetConnectAttr, SQLRETURN(SQLHDBC ConnectionHandle, SQLINTEGER Attribute, SQLPOINTER Value, SQLINTEGER StringLength));
   LIBL_STDCALL(SQLSetConnectOption, SQLRETURN(SQLHDBC ConnectionHandle, SQLUSMALLINT Option, SQLULEN Value));
   LIBL_STDCALL(SQLSetCursorName, SQLRETURN(SQLHSTMT StatementHandle, SQLCHAR *CursorName, SQLSMALLINT NameLength));
   LIBL_STDCALL(SQLSetDescField, SQLRETURN(SQLHDESC DescriptorHandle, SQLSMALLINT RecNumber, SQLSMALLINT FieldIdentifier, SQLPOINTER Value, SQLINTEGER BufferLength));
   LIBL_STDCALL(SQLSetDescRec, SQLRETURN(SQLHDESC DescriptorHandle, SQLSMALLINT RecNumber, SQLSMALLINT Type, SQLSMALLINT SubType, SQLLEN Length, SQLSMALLINT Precision, SQLSMALLINT Scale, SQLPOINTER Data, SQLLEN *StringLength, SQLLEN *Indicator));
   LIBL_STDCALL(SQLSetEnvAttr, SQLRETURN(SQLHENV EnvironmentHandle, SQLINTEGER Attribute, SQLPOINTER Value, SQLINTEGER StringLength));
   LIBL_STDCALL(SQLSetParam, SQLRETURN(SQLHSTMT StatementHandle, SQLUSMALLINT ParameterNumber, SQLSMALLINT ValueType, SQLSMALLINT ParameterType, SQLULEN LengthPrecision, SQLSMALLINT ParameterScale, SQLPOINTER ParameterValue, SQLLEN *StrLen_or_Ind));
   LIBL_STDCALL(SQLSetStmtAttr, SQLRETURN(SQLHSTMT StatementHandle, SQLINTEGER Attribute, SQLPOINTER Value, SQLINTEGER StringLength));
   LIBL_STDCALL(SQLSetStmtOption, SQLRETURN(SQLHSTMT StatementHandle, SQLUSMALLINT Option, SQLULEN Value));
   LIBL_STDCALL(SQLSpecialColumns, SQLRETURN(SQLHSTMT StatementHandle, SQLUSMALLINT IdentifierType, SQLCHAR *CatalogName, SQLSMALLINT NameLength1, SQLCHAR *SchemaName, SQLSMALLINT NameLength2, SQLCHAR *TableName, SQLSMALLINT NameLength3, SQLUSMALLINT Scope, SQLUSMALLINT Nullable));
   LIBL_STDCALL(SQLStatistics, SQLRETURN(SQLHSTMT StatementHandle, SQLCHAR *CatalogName, SQLSMALLINT NameLength1, SQLCHAR *SchemaName, SQLSMALLINT NameLength2, SQLCHAR *TableName, SQLSMALLINT NameLength3, SQLUSMALLINT Unique, SQLUSMALLINT Reserved));
   LIBL_STDCALL(SQLTables, SQLRETURN(SQLHSTMT StatementHandle, SQLCHAR *CatalogName, SQLSMALLINT NameLength1, SQLCHAR *SchemaName, SQLSMALLINT NameLength2, SQLCHAR *TableName, SQLSMALLINT NameLength3, SQLCHAR *TableType, SQLSMALLINT NameLength4));
   LIBL_STDCALL(SQLTransact, SQLRETURN(SQLHENV EnvironmentHandle, SQLHDBC ConnectionHandle, SQLUSMALLINT CompletionType));

   // sqlucode.h
   LIBL_STDCALL(SQLColAttributeW, SQLRETURN(SQLHSTMT hstmt, SQLUSMALLINT iCol, SQLUSMALLINT iField, SQLPOINTER pCharAttr, SQLSMALLINT cbCharAttrMax, SQLSMALLINT *pcbCharAttr, SQLLEN *pNumAttr));
   LIBL_STDCALL(SQLColAttributesW, SQLRETURN(SQLHSTMT hstmt, SQLUSMALLINT icol, SQLUSMALLINT fDescType, SQLPOINTER rgbDesc, SQLSMALLINT cbDescMax, SQLSMALLINT *pcbDesc, SQLLEN *pfDesc));
   LIBL_STDCALL(SQLConnectW, SQLRETURN(SQLHDBC hdbc, SQLWCHAR *szDSN, SQLSMALLINT cbDSN, SQLWCHAR *szUID, SQLSMALLINT cbUID, SQLWCHAR *szAuthStr, SQLSMALLINT cbAuthStr));
   LIBL_STDCALL(SQLDescribeColW, SQLRETURN(SQLHSTMT hstmt, SQLUSMALLINT icol, SQLWCHAR *szColName, SQLSMALLINT cbColNameMax, SQLSMALLINT *pcbColName, SQLSMALLINT *pfSqlType, SQLULEN *pcbColDef, SQLSMALLINT *pibScale, SQLSMALLINT *pfNullable));
   LIBL_STDCALL(SQLErrorW, SQLRETURN(SQLHENV henv, SQLHDBC hdbc, SQLHSTMT hstmt, SQLWCHAR *szSqlState, SQLINTEGER *pfNativeError, SQLWCHAR *szErrorMsg, SQLSMALLINT cbErrorMsgMax, SQLSMALLINT *pcbErrorMsg));
   LIBL_STDCALL(SQLExecDirectW, SQLRETURN(SQLHSTMT hstmt, SQLWCHAR *szSqlStr, SQLINTEGER cbSqlStr));
   LIBL_STDCALL(SQLGetConnectAttrW, SQLRETURN(SQLHDBC hdbc, SQLINTEGER fAttribute, SQLPOINTER rgbValue, SQLINTEGER cbValueMax, SQLINTEGER *pcbValue));
   LIBL_STDCALL(SQLGetCursorNameW, SQLRETURN(SQLHSTMT hstmt, SQLWCHAR *szCursor, SQLSMALLINT cbCursorMax, SQLSMALLINT *pcbCursor));
   LIBL_STDCALL(SQLSetDescFieldW, SQLRETURN(SQLHDESC DescriptorHandle, SQLSMALLINT RecNumber, SQLSMALLINT FieldIdentifier, SQLPOINTER Value, SQLINTEGER BufferLength));
   LIBL_STDCALL(SQLGetDescFieldW, SQLRETURN(SQLHDESC hdesc, SQLSMALLINT iRecord, SQLSMALLINT iField, SQLPOINTER rgbValue, SQLINTEGER cbValueMax, SQLINTEGER *pcbValue));
   LIBL_STDCALL(SQLGetDescRecW, SQLRETURN(SQLHDESC hdesc, SQLSMALLINT iRecord, SQLWCHAR *szName, SQLSMALLINT cbNameMax, SQLSMALLINT *pcbName, SQLSMALLINT *pfType, SQLSMALLINT *pfSubType, SQLLEN *pLength, SQLSMALLINT *pPrecision, SQLSMALLINT *pScale, SQLSMALLINT *pNullable));
   LIBL_STDCALL(SQLGetDiagFieldW, SQLRETURN(SQLSMALLINT fHandleType, SQLHANDLE handle, SQLSMALLINT iRecord, SQLSMALLINT fDiagField, SQLPOINTER rgbDiagInfo, SQLSMALLINT cbDiagInfoMax, SQLSMALLINT *pcbDiagInfo));
   LIBL_STDCALL(SQLGetDiagRecW, SQLRETURN(SQLSMALLINT fHandleType, SQLHANDLE handle, SQLSMALLINT iRecord, SQLWCHAR *szSqlState, SQLINTEGER *pfNativeError, SQLWCHAR *szErrorMsg, SQLSMALLINT cbErrorMsgMax, SQLSMALLINT *pcbErrorMsg));
   LIBL_STDCALL(SQLPrepareW, SQLRETURN(SQLHSTMT hstmt, SQLWCHAR *szSqlStr, SQLINTEGER cbSqlStr));
   LIBL_STDCALL(SQLSetConnectAttrW, SQLRETURN(SQLHDBC hdbc, SQLINTEGER fAttribute, SQLPOINTER rgbValue, SQLINTEGER cbValue));
   LIBL_STDCALL(SQLSetCursorNameW, SQLRETURN(SQLHSTMT hstmt, SQLWCHAR *szCursor, SQLSMALLINT cbCursor));
   LIBL_STDCALL(SQLColumnsW, SQLRETURN(SQLHSTMT hstmt, SQLWCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLWCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLWCHAR *szTableName, SQLSMALLINT cbTableName, SQLWCHAR *szColumnName, SQLSMALLINT cbColumnName));
   LIBL_STDCALL(SQLGetConnectOptionW, SQLRETURN(SQLHDBC hdbc, SQLUSMALLINT fOption, SQLPOINTER pvParam));
   LIBL_STDCALL(SQLGetInfoW, SQLRETURN(SQLHDBC hdbc, SQLUSMALLINT fInfoType, SQLPOINTER rgbInfoValue, SQLSMALLINT cbInfoValueMax, SQLSMALLINT *pcbInfoValue));
   LIBL_STDCALL(SQLGetTypeInfoW, SQLRETURN(SQLHSTMT StatementHandle, SQLSMALLINT DataType));
   LIBL_STDCALL(SQLSetConnectOptionW, SQLRETURN(SQLHDBC hdbc, SQLUSMALLINT fOption, SQLULEN vParam));
   LIBL_STDCALL(SQLSpecialColumnsW, SQLRETURN(SQLHSTMT hstmt, SQLUSMALLINT fColType, SQLWCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLWCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLWCHAR *szTableName, SQLSMALLINT cbTableName, SQLUSMALLINT fScope, SQLUSMALLINT fNullable));
   LIBL_STDCALL(SQLStatisticsW, SQLRETURN(SQLHSTMT hstmt, SQLWCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLWCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLWCHAR *szTableName, SQLSMALLINT cbTableName, SQLUSMALLINT fUnique, SQLUSMALLINT fAccuracy));
   LIBL_STDCALL(SQLTablesW, SQLRETURN(SQLHSTMT hstmt, SQLWCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLWCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLWCHAR *szTableName, SQLSMALLINT cbTableName, SQLWCHAR *szTableType, SQLSMALLINT cbTableType));
   LIBL_STDCALL(SQLDataSourcesW, SQLRETURN(SQLHENV henv, SQLUSMALLINT fDirection, SQLWCHAR *szDSN, SQLSMALLINT cbDSNMax, SQLSMALLINT *pcbDSN, SQLWCHAR *szDescription, SQLSMALLINT cbDescriptionMax, SQLSMALLINT *pcbDescription));
   LIBL_STDCALL(SQLDriverConnectW, SQLRETURN(SQLHDBC hdbc, SQLHWND hwnd, SQLWCHAR *szConnStrIn, SQLSMALLINT cbConnStrIn, SQLWCHAR *szConnStrOut, SQLSMALLINT cbConnStrOutMax, SQLSMALLINT *pcbConnStrOut, SQLUSMALLINT fDriverCompletion));
   LIBL_STDCALL(SQLBrowseConnectW, SQLRETURN(SQLHDBC hdbc, SQLWCHAR *szConnStrIn, SQLSMALLINT cbConnStrIn, SQLWCHAR *szConnStrOut, SQLSMALLINT cbConnStrOutMax, SQLSMALLINT *pcbConnStrOut));
   LIBL_STDCALL(SQLColumnPrivilegesW, SQLRETURN(SQLHSTMT hstmt, SQLWCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLWCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLWCHAR *szTableName, SQLSMALLINT cbTableName, SQLWCHAR *szColumnName, SQLSMALLINT cbColumnName));
   LIBL_STDCALL(SQLGetStmtAttrW, SQLRETURN(SQLHSTMT hstmt, SQLINTEGER fAttribute, SQLPOINTER rgbValue, SQLINTEGER cbValueMax, SQLINTEGER *pcbValue));
   LIBL_STDCALL(SQLSetStmtAttrW, SQLRETURN(SQLHSTMT hstmt, SQLINTEGER fAttribute, SQLPOINTER rgbValue, SQLINTEGER cbValueMax));
   LIBL_STDCALL(SQLForeignKeysW, SQLRETURN(SQLHSTMT hstmt, SQLWCHAR *szPkCatalogName, SQLSMALLINT cbPkCatalogName, SQLWCHAR *szPkSchemaName, SQLSMALLINT cbPkSchemaName, SQLWCHAR *szPkTableName, SQLSMALLINT cbPkTableName, SQLWCHAR *szFkCatalogName, SQLSMALLINT cbFkCatalogName, SQLWCHAR *szFkSchemaName, SQLSMALLINT cbFkSchemaName, SQLWCHAR *szFkTableName, SQLSMALLINT cbFkTableName));
   LIBL_STDCALL(SQLNativeSqlW, SQLRETURN(SQLHDBC hdbc, SQLWCHAR *szSqlStrIn, SQLINTEGER cbSqlStrIn, SQLWCHAR *szSqlStr, SQLINTEGER cbSqlStrMax, SQLINTEGER *pcbSqlStr));
   LIBL_STDCALL(SQLPrimaryKeysW, SQLRETURN(SQLHSTMT hstmt, SQLWCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLWCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLWCHAR *szTableName, SQLSMALLINT cbTableName));
   LIBL_STDCALL(SQLProcedureColumnsW, SQLRETURN(SQLHSTMT hstmt, SQLWCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLWCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLWCHAR *szProcName, SQLSMALLINT cbProcName, SQLWCHAR *szColumnName, SQLSMALLINT cbColumnName));
   LIBL_STDCALL(SQLProceduresW, SQLRETURN(SQLHSTMT hstmt, SQLWCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLWCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLWCHAR *szProcName, SQLSMALLINT cbProcName));
   LIBL_STDCALL(SQLTablePrivilegesW, SQLRETURN(SQLHSTMT hstmt, SQLWCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLWCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLWCHAR *szTableName, SQLSMALLINT cbTableName));
   LIBL_STDCALL(SQLDriversW, SQLRETURN(SQLHENV henv, SQLUSMALLINT fDirection, SQLWCHAR *szDriverDesc, SQLSMALLINT cbDriverDescMax, SQLSMALLINT *pcbDriverDesc, SQLWCHAR *szDriverAttributes, SQLSMALLINT cbDrvrAttrMax, SQLSMALLINT *pcbDrvrAttr));
   LIBL_STDCALL(SQLColAttributeA, SQLRETURN(SQLHSTMT hstmt, SQLSMALLINT iCol, SQLSMALLINT iField, SQLPOINTER pCharAttr, SQLSMALLINT cbCharAttrMax, SQLSMALLINT *pcbCharAttr, SQLLEN *pNumAttr));
   LIBL_STDCALL(SQLColAttributesA, SQLRETURN(SQLHSTMT hstmt, SQLUSMALLINT icol, SQLUSMALLINT fDescType, SQLPOINTER rgbDesc, SQLSMALLINT cbDescMax, SQLSMALLINT *pcbDesc, SQLLEN *pfDesc));
   LIBL_STDCALL(SQLConnectA, SQLRETURN(SQLHDBC hdbc, SQLCHAR *szDSN, SQLSMALLINT cbDSN, SQLCHAR *szUID, SQLSMALLINT cbUID, SQLCHAR *szAuthStr, SQLSMALLINT cbAuthStr));
   LIBL_STDCALL(SQLDescribeColA, SQLRETURN(SQLHSTMT hstmt, SQLUSMALLINT icol, SQLCHAR *szColName, SQLSMALLINT cbColNameMax, SQLSMALLINT *pcbColName, SQLSMALLINT *pfSqlType, SQLULEN *pcbColDef, SQLSMALLINT *pibScale, SQLSMALLINT *pfNullable));
   LIBL_STDCALL(SQLErrorA, SQLRETURN(SQLHENV henv, SQLHDBC hdbc, SQLHSTMT hstmt, SQLCHAR *szSqlState, SQLINTEGER *pfNativeError, SQLCHAR *szErrorMsg, SQLSMALLINT cbErrorMsgMax, SQLSMALLINT *pcbErrorMsg));
   LIBL_STDCALL(SQLExecDirectA, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szSqlStr, SQLINTEGER cbSqlStr));
   LIBL_STDCALL(SQLGetConnectAttrA, SQLRETURN(SQLHDBC hdbc, SQLINTEGER fAttribute, SQLPOINTER rgbValue, SQLINTEGER cbValueMax, SQLINTEGER *pcbValue));
   LIBL_STDCALL(SQLGetCursorNameA, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCursor, SQLSMALLINT cbCursorMax, SQLSMALLINT *pcbCursor));
   LIBL_STDCALL(SQLGetDescFieldA, SQLRETURN(SQLHDESC hdesc, SQLSMALLINT iRecord, SQLSMALLINT iField, SQLPOINTER rgbValue, SQLINTEGER cbValueMax, SQLINTEGER *pcbValue));
   LIBL_STDCALL(SQLGetDescRecA, SQLRETURN(SQLHDESC hdesc, SQLSMALLINT iRecord, SQLCHAR *szName, SQLSMALLINT cbNameMax, SQLSMALLINT *pcbName, SQLSMALLINT *pfType, SQLSMALLINT *pfSubType, SQLLEN *pLength, SQLSMALLINT *pPrecision, SQLSMALLINT *pScale, SQLSMALLINT *pNullable));
   LIBL_STDCALL(SQLGetDiagFieldA, SQLRETURN(SQLSMALLINT fHandleType, SQLHANDLE handle, SQLSMALLINT iRecord, SQLSMALLINT fDiagField, SQLPOINTER rgbDiagInfo, SQLSMALLINT cbDiagInfoMax, SQLSMALLINT *pcbDiagInfo));
   LIBL_STDCALL(SQLGetDiagRecA, SQLRETURN(SQLSMALLINT fHandleType, SQLHANDLE handle, SQLSMALLINT iRecord, SQLCHAR *szSqlState, SQLINTEGER *pfNativeError, SQLCHAR *szErrorMsg, SQLSMALLINT cbErrorMsgMax, SQLSMALLINT *pcbErrorMsg));
   LIBL_STDCALL(SQLGetStmtAttrA, SQLRETURN(SQLHSTMT hstmt, SQLINTEGER fAttribute, SQLPOINTER rgbValue, SQLINTEGER cbValueMax, SQLINTEGER *pcbValue));
   LIBL_STDCALL(SQLGetTypeInfoA, SQLRETURN(SQLHSTMT StatementHandle, SQLSMALLINT DataTyoe));
   LIBL_STDCALL(SQLPrepareA, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szSqlStr, SQLINTEGER cbSqlStr));
   LIBL_STDCALL(SQLSetConnectAttrA, SQLRETURN(SQLHDBC hdbc, SQLINTEGER fAttribute, SQLPOINTER rgbValue, SQLINTEGER cbValue));
   LIBL_STDCALL(SQLSetCursorNameA, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCursor, SQLSMALLINT cbCursor));
   LIBL_STDCALL(SQLColumnsA, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLCHAR *szTableName, SQLSMALLINT cbTableName, SQLCHAR *szColumnName, SQLSMALLINT cbColumnName));
   LIBL_STDCALL(SQLGetConnectOptionA, SQLRETURN(SQLHDBC hdbc, SQLUSMALLINT fOption, SQLPOINTER pvParam));
   LIBL_STDCALL(SQLGetInfoA, SQLRETURN(SQLHDBC hdbc, SQLUSMALLINT fInfoType, SQLPOINTER rgbInfoValue, SQLSMALLINT cbInfoValueMax, SQLSMALLINT *pcbInfoValue));
   //LIBL_STDCALL(SQLGetStmtOptionA, SQLRETURN(SQLHSTMT hstmt, SQLUSMALLINT fOption, SQLPOINTER pvParam));
   LIBL_STDCALL(SQLSetConnectOptionA, SQLRETURN(SQLHDBC hdbc, SQLUSMALLINT fOption, SQLULEN vParam));
   LIBL_STDCALL(SQLSetStmtOptionA, SQLRETURN(SQLHSTMT hstmt, SQLUSMALLINT fOption, SQLULEN vParam));
   LIBL_STDCALL(SQLSpecialColumnsA, SQLRETURN(SQLHSTMT hstmt, SQLUSMALLINT fColType, SQLCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLCHAR *szTableName, SQLSMALLINT cbTableName, SQLUSMALLINT fScope, SQLUSMALLINT fNullable));
   LIBL_STDCALL(SQLStatisticsA, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLCHAR *szTableName, SQLSMALLINT cbTableName, SQLUSMALLINT fUnique, SQLUSMALLINT fAccuracy));
   LIBL_STDCALL(SQLTablesA, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLCHAR *szTableName, SQLSMALLINT cbTableName, SQLCHAR *szTableType, SQLSMALLINT cbTableType));
   LIBL_STDCALL(SQLDataSourcesA, SQLRETURN(SQLHENV henv, SQLUSMALLINT fDirection, SQLCHAR *szDSN, SQLSMALLINT cbDSNMax, SQLSMALLINT *pcbDSN, SQLCHAR *szDescription, SQLSMALLINT cbDescriptionMax, SQLSMALLINT *pcbDescription));
   LIBL_STDCALL(SQLDriverConnectA, SQLRETURN(SQLHDBC hdbc, SQLHWND hwnd, SQLCHAR *szConnStrIn, SQLSMALLINT cbConnStrIn, SQLCHAR *szConnStrOut, SQLSMALLINT cbConnStrOutMax, SQLSMALLINT *pcbConnStrOut, SQLUSMALLINT fDriverCompletion));
   LIBL_STDCALL(SQLBrowseConnectA, SQLRETURN(SQLHDBC hdbc, SQLCHAR *szConnStrIn, SQLSMALLINT cbConnStrIn, SQLCHAR *szConnStrOut, SQLSMALLINT cbConnStrOutMax, SQLSMALLINT *pcbConnStrOut));
   LIBL_STDCALL(SQLColumnPrivilegesA, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLCHAR *szTableName, SQLSMALLINT cbTableName, SQLCHAR *szColumnName, SQLSMALLINT cbColumnName));
   //LIBL_STDCALL(SQLDescribeParamA, SQLRETURN(SQLHSTMT hstmt, SQLUSMALLINT ipar, SQLSMALLINT *pfSqlType, SQLUINTEGER *pcbParamDef, SQLSMALLINT *pibScale, SQLSMALLINT *pfNullable));
   LIBL_STDCALL(SQLForeignKeysA, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szPkCatalogName, SQLSMALLINT cbPkCatalogName, SQLCHAR *szPkSchemaName, SQLSMALLINT cbPkSchemaName, SQLCHAR *szPkTableName, SQLSMALLINT cbPkTableName, SQLCHAR *szFkCatalogName, SQLSMALLINT cbFkCatalogName, SQLCHAR *szFkSchemaName, SQLSMALLINT cbFkSchemaName, SQLCHAR *szFkTableName, SQLSMALLINT cbFkTableName));
   LIBL_STDCALL(SQLNativeSqlA, SQLRETURN(SQLHDBC hdbc, SQLCHAR *szSqlStrIn, SQLINTEGER cbSqlStrIn, SQLCHAR *szSqlStr, SQLINTEGER cbSqlStrMax, SQLINTEGER *pcbSqlStr));
   LIBL_STDCALL(SQLPrimaryKeysA, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLCHAR *szTableName, SQLSMALLINT cbTableName));
   LIBL_STDCALL(SQLProcedureColumnsA, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLCHAR *szProcName, SQLSMALLINT cbProcName, SQLCHAR *szColumnName, SQLSMALLINT cbColumnName));
   LIBL_STDCALL(SQLProceduresA, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLCHAR *szProcName, SQLSMALLINT cbProcName));
   LIBL_STDCALL(SQLTablePrivilegesA, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLCHAR *szTableName, SQLSMALLINT cbTableName));
   LIBL_STDCALL(SQLDriversA, SQLRETURN(SQLHENV henv, SQLUSMALLINT fDirection, SQLCHAR *szDriverDesc, SQLSMALLINT cbDriverDescMax, SQLSMALLINT *pcbDriverDesc, SQLCHAR *szDriverAttributes, SQLSMALLINT cbDrvrAttrMax, SQLSMALLINT *pcbDrvrAttr));

   // sqlext.h
   LIBL_STDCALL(SQLDriverConnect, SQLRETURN(SQLHDBC hdbc, SQLHWND hwnd, SQLCHAR *szConnStrIn, SQLSMALLINT cbConnStrIn, SQLCHAR *szConnStrOut, SQLSMALLINT cbConnStrOutMax, SQLSMALLINT *pcbConnStrOut, SQLUSMALLINT fDriverCompletion));
   LIBL_STDCALL(SQLBrowseConnect, SQLRETURN(SQLHDBC hdbc, SQLCHAR *szConnStrIn, SQLSMALLINT cbConnStrIn, SQLCHAR *szConnStrOut, SQLSMALLINT cbConnStrOutMax, SQLSMALLINT *pcbConnStrOut));
   LIBL_STDCALL(SQLBulkOperations, SQLRETURN(SQLHSTMT StatementHandle, SQLSMALLINT Operation));
   LIBL_STDCALL(SQLColAttributes, SQLRETURN(SQLHSTMT hstmt, SQLUSMALLINT icol, SQLUSMALLINT fDescType, SQLPOINTER rgbDesc, SQLSMALLINT cbDescMax, SQLSMALLINT *pcbDesc, SQLLEN *pfDesc));
   LIBL_STDCALL(SQLColumnPrivileges, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLCHAR *szTableName, SQLSMALLINT cbTableName, SQLCHAR *szColumnName, SQLSMALLINT cbColumnName));
   LIBL_STDCALL(SQLDescribeParam, SQLRETURN(SQLHSTMT hstmt, SQLUSMALLINT ipar, SQLSMALLINT *pfSqlType, SQLULEN *pcbParamDef, SQLSMALLINT *pibScale, SQLSMALLINT *pfNullable));
   LIBL_STDCALL(SQLExtendedFetch, SQLRETURN(SQLHSTMT hstmt, SQLUSMALLINT fFetchType, SQLLEN irow, SQLULEN *pcrow, SQLUSMALLINT *rgfRowStatus));
   LIBL_STDCALL(SQLForeignKeys, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szPkCatalogName, SQLSMALLINT cbPkCatalogName, SQLCHAR *szPkSchemaName, SQLSMALLINT cbPkSchemaName, SQLCHAR *szPkTableName, SQLSMALLINT cbPkTableName, SQLCHAR *szFkCatalogName, SQLSMALLINT cbFkCatalogName, SQLCHAR *szFkSchemaName, SQLSMALLINT cbFkSchemaName, SQLCHAR *szFkTableName, SQLSMALLINT cbFkTableName));
   LIBL_STDCALL(SQLMoreResults, SQLRETURN(SQLHSTMT hstmt));
   LIBL_STDCALL(SQLNativeSql, SQLRETURN(SQLHDBC hdbc, SQLCHAR *szSqlStrIn, SQLINTEGER cbSqlStrIn, SQLCHAR *szSqlStr, SQLINTEGER cbSqlStrMax, SQLINTEGER *pcbSqlStr));
   LIBL_STDCALL(SQLNumParams, SQLRETURN(SQLHSTMT hstmt, SQLSMALLINT *pcpar));
   LIBL_STDCALL(SQLParamOptions, SQLRETURN(SQLHSTMT hstmt, SQLULEN crow, SQLULEN *pirow));
   LIBL_STDCALL(SQLPrimaryKeys, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLCHAR *szTableName, SQLSMALLINT cbTableName));
   LIBL_STDCALL(SQLProcedureColumns, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLCHAR *szProcName, SQLSMALLINT cbProcName, SQLCHAR *szColumnName, SQLSMALLINT cbColumnName));
   LIBL_STDCALL(SQLProcedures, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLCHAR *szProcName, SQLSMALLINT cbProcName));
   LIBL_STDCALL(SQLSetPos, SQLRETURN(SQLHSTMT hstmt, SQLSETPOSIROW irow, SQLUSMALLINT fOption, SQLUSMALLINT fLock));
   LIBL_STDCALL(SQLTablePrivileges, SQLRETURN(SQLHSTMT hstmt, SQLCHAR *szCatalogName, SQLSMALLINT cbCatalogName, SQLCHAR *szSchemaName, SQLSMALLINT cbSchemaName, SQLCHAR *szTableName, SQLSMALLINT cbTableName));
   LIBL_STDCALL(SQLDrivers, SQLRETURN(SQLHENV henv, SQLUSMALLINT fDirection, SQLCHAR *szDriverDesc, SQLSMALLINT cbDriverDescMax, SQLSMALLINT *pcbDriverDesc, SQLCHAR *szDriverAttributes, SQLSMALLINT cbDrvrAttrMax, SQLSMALLINT *pcbDrvrAttr));
   LIBL_STDCALL(SQLBindParameter, SQLRETURN(SQLHSTMT hstmt, SQLUSMALLINT ipar, SQLSMALLINT fParamType, SQLSMALLINT fCType, SQLSMALLINT fSqlType, SQLULEN cbColDef, SQLSMALLINT ibScale, SQLPOINTER rgbValue, SQLLEN cbValueMax, SQLLEN *pcbValue));
   LIBL_STDCALL(SQLAllocHandleStd, SQLRETURN(SQLSMALLINT fHandleType, SQLHANDLE hInput, SQLHANDLE *phOutput));

};
